name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
    - title: 'Breaking Changes'
      labels:
        - 'breaking'
    - title: 'Features'
      labels: 
        - 'feature'
    - title: 'Bug Fixes'
      labels: 
        - 'bugfix'
    - title: 'Dependencies'
      labels: 
        - 'dependency'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
  patch:
    labels:
      - 'patch'
      - 'bugfix'
  default: minor
exclude-labels: 
    - 'skip-changelog'
template: |
  ## What’s Changed
    $CHANGES
