name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
    - title: 'Features'
      labels: 
        - 'feature'
        - 'enhancement'
    - title: 'Bug Fixes'
      labels: 
        - 'fix'
        - 'bug'
        - 'bugfix'
    - title: 'Dependencies'
      labels: 'dependency'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: minor
exclude-labels: 
    - 'skip-changelog'
template: |
  ## What’s Changed
    $CHANGES
