name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
    - title: 'Features'
      labels: 'feature'
    - title: 'Bug Fixes'
      labels: 'fix'
change-template: | 
    '- $TITLE @$AUTHOR (#$NUMBER)'
    ' - $Body'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
exclude-labels: 
    - 'skip-changelog'
template: |
  ## What’s Changed
    $CHANGES
