# spins up travis server to use python 3.6
#
language: python
python:
    - "3.6"

services:
    - docker

before_script: pip install docker-compose

jobs:
    include:
    - stage: flake8
      name: "flake8"
      script: flake8
    - stage: deploy
      name: "Deploy to Quay"
      script: skip
      deploy:
        provider: script
        script: ./scripts/deploy.sh $TRAVIS_TAG
        on:
          tags: true
          condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
stages:
  - flake8
  - deploy
# Control the branches that get built.
branches:
    only:
      - master
      - /^v[0-9]+\.[0-9]+\.[0-9]+/